services:
  app_mongo_aml:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.mongo_aml
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $APP_MONGO_AML_HASURA_SERVICE_TOKEN_SECRET
      MONGODB_DATABASE_URI: $APP_MONGO_AML_MONGODB_DATABASE_URI
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_MONGO_AML_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_MONGO_AML_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 9457:8080
